# Generated by Django 6.0 on 2026-01-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/category_icons/'),
        ),
    ]
